In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("Default.csv")
data

default student      balance       income
0         No      No   729.526495  44361.62507
1         No     Yes   817.180407  12106.13470
2         No      No  1073.549164  31767.13895
3         No      No   529.250605  35704.49394
4         No      No   785.655883  38463.49588
...      ...     ...          ...          ...
9995      No      No   711.555020  52992.37891
9996      No      No   757.962918  19660.72177
9997      No      No   845.411989  58636.15698
9998      No      No  1569.009053  36669.11236
9999      No     Yes   200.922183  16862.95232

[10000 rows x 4 columns]

In [3]:
data.head()

default student      balance       income
0      No      No   729.526495  44361.62507
1      No     Yes   817.180407  12106.13470
2      No      No  1073.549164  31767.13895
3      No      No   529.250605  35704.49394
4      No      No   785.655883  38463.49588

In [4]:
data.isna().sum()

default    0
student    0
balance    0
income     0
dtype: int64

In [5]:
data["default"].nunique()

2

In [6]:
data["default"].count()

10000

In [7]:
data["default"].value_counts()

default
No     9667
Yes     333
Name: count, dtype: int64

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   default  10000 non-null  object 
 1   student  10000 non-null  object 
 2   balance  10000 non-null  float64
 3   income   10000 non-null  float64
dtypes: float64(2), object(2)
memory usage: 312.6+ KB


In [9]:
data.describe()

balance        income
count  10000.000000  10000.000000
mean     835.374886  33516.981876
std      483.714985  13336.639563
min        0.000000    771.967729
25%      481.731105  21340.462905
50%      823.636973  34552.644800
75%     1166.308387  43807.729275
max     2654.322576  73554.233500

decide x and y

In [10]:
x=data.iloc[:,2:4]
y=data.iloc[:,0]
x


balance       income
0      729.526495  44361.62507
1      817.180407  12106.13470
2     1073.549164  31767.13895
3      529.250605  35704.49394
4      785.655883  38463.49588
...           ...          ...
9995   711.555020  52992.37891
9996   757.962918  19660.72177
9997   845.411989  58636.15698
9998  1569.009053  36669.11236
9999   200.922183  16862.95232

[10000 rows x 2 columns]

In [11]:
y

0       No
1       No
2       No
3       No
4       No
        ..
9995    No
9996    No
9997    No
9998    No
9999    No
Name: default, Length: 10000, dtype: object

#Transformation

In [12]:
#for distance calculation we done transformation it take it in one scale

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
minmax=MinMaxScaler()
x_tran=minmax.fit_transform(x)
x_tran

array([[0.2748447 , 0.59890492],
       [0.30786778, 0.15572704],
       [0.40445316, 0.42586159],
       ...,
       [0.31850386, 0.79503144],
       [0.59111468, 0.49321279],
       [0.07569622, 0.22108386]])

In [15]:
x_tran=pd.DataFrame(x_tran)


In [16]:
x_tran.describe()

0             1
count  10000.000000  10000.000000
mean       0.314722      0.449904
std        0.182237      0.183240
min        0.000000      0.000000
25%        0.181489      0.282603
50%        0.310300      0.464133
75%        0.439400      0.591295
max        1.000000      1.000000

split data train and test

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x_tran,y,test_size=0.2,random_state=0)

In [19]:
x_train.size

16000

In [20]:
x_test.shape

(2000, 2)

In [21]:
from sklearn.neighbors import KNeighborsClassifier

In [22]:
knn=KNeighborsClassifier(n_neighbors=3,metric="euclidean")

In [23]:
knn.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [24]:
train_pred=knn.predict(x_train)

In [25]:
train_pred

array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [26]:
test_pred=knn.predict(x_test)

In [27]:
test_pred

array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

Evaluation check

In [28]:
from sklearn.metrics import accuracy_score

In [29]:
train_acc=accuracy_score(y_train,train_pred)
train_acc

0.977

In [30]:
test_acc=accuracy_score(y_test,test_pred)
test_acc

0.9655

Confusion metrix 

In [31]:
from sklearn.metrics import confusion_matrix,precision_score
confusion_matrix(y_train,train_pred)        #Accuracy=(TP+TN)/(TP+FP+FN+TN)

array([[7695,   46],
       [ 138,  121]], dtype=int64)

Precision_score

In [32]:
precision_score(y_train,train_pred,pos_label="No")

0.9823822290310226

#Using Sampling Techniques

In [33]:
from imblearn.under_sampling import RandomUnderSampler

In [34]:
runder=RandomUnderSampler()

In [35]:
x_train_under,y_train_under=runder.fit_resample(x_train,y_train)

In [36]:
y_train_under.value_counts()

default
No     259
Yes    259
Name: count, dtype: int64

In [37]:
x_test_under,y_test_under=runder.fit_resample(x_test,y_test)

In [38]:
y_test_under.value_counts()

default
No     74
Yes    74
Name: count, dtype: int64

In [39]:
knn=KNeighborsClassifier(n_neighbors=5,metric="euclidean")
knn.fit(x_train_under,y_train_under)
train_pred=knn.predict(x_train_under)  #UnderFitting
test_pred=knn.predict(x_test_under)

In [40]:
train_acc=accuracy_score(y_train_under,train_pred)
train_acc

0.8803088803088803

In [41]:
confusion_matrix(y_train_under,train_pred)

array([[218,  41],
       [ 21, 238]], dtype=int64)

In [42]:
test_acc=accuracy_score(y_test_under,test_pred)

In [43]:
test_acc

0.8581081081081081

In [44]:
from imblearn.over_sampling import RandomOverSampler
rover=RandomOverSampler()

In [45]:
x_train_over,y_train_over=rover.fit_resample(x_train,y_train)
x_test_over,y_test_over=rover.fit_resample(x_test,y_test)

In [46]:
y_train_over.value_counts()

default
No     7741
Yes    7741
Name: count, dtype: int64

In [47]:
knn=KNeighborsClassifier(n_neighbors=5,metric="euclidean")
knn.fit(x_train_over,y_train_over)
train_pred=knn.predict(x_train_over)   #OverFitting 
test_pred=knn.predict(x_test_over)

In [48]:
accuracy_score(y_train_over,train_pred)

0.9799767471902855

In [49]:
accuracy_score(y_test_over,test_pred)

0.7606438213914849

In [50]:
from imblearn.over_sampling import SMOTE
sm=SMOTE()
x_train_sm,y_train_sm=sm.fit_resample(x_train,y_train)
x_test_sm,y_test_sm=sm.fit_resample(x_test,y_test)

In [51]:
x_train_sm.value_counts()

0         1       
0.000000  0.117467    1
0.615854  0.513405    1
0.617162  0.635153    1
0.617164  0.501865    1
0.617253  0.344081    1
                     ..
0.377252  0.254773    1
0.377417  0.329747    1
0.377442  0.439347    1
0.377552  0.600058    1
1.000000  0.290708    1
Name: count, Length: 15482, dtype: int64

In [52]:
knn=KNeighborsClassifier(n_neighbors=5,metric="euclidean")
knn.fit(x_train_sm,y_train_sm)
train_pred=knn.predict(x_train_sm)   #OverFitting 
test_pred=knn.predict(x_test_sm)

In [53]:
accuracy_score(y_train_sm,train_pred)


0.9450329414804289

In [54]:
accuracy_score(y_test_sm,test_pred)

0.8008826583592938